### Apply


### Zadanie 1: Klasyfikacja tekstowa

Masz kolumnę z opisami produktów. 

Użyj apply, aby stworzyć kolumnę 'kategoria_dlugosc' z wartościami: 

- 'krótki' (<50 znaków), 
- 'średni' (50-100), 
- 'długi' (>100). 

Następnie zlicz słowa w opisie.

In [2]:
import pandas as pd

df = pd.DataFrame({
    'id': range(1, 6),
    'opis': [
        'Małe krzesło',
        'Eleganckie biurko z drewna dębowego z szufladami',
        'Kompaktowy laptop do pracy biurowej z procesorem i7, 16GB RAM i dyskiem SSD 512GB, idealny do codziennych zadań',
        'Lampa',
        'Wygodna kanapa trzysegmentowa w kolorze szarym z funkcją spania'
    ]
})

Nowe kolumny: 'kategoria_dlugosc', 'liczba_slow'

In [7]:
def classify_sentence(text):
    n = len(text)
    if n < 50:
        return 'krótki'
    elif n < 100:
        return 'średni'
    return 'długi'

# -------------
# Kategoria długość: ilosć znaków
# ---------------
# _ = df['opis'].apply(lambda x: print(f"wyświetlam wiersz: {x}") or x)
df['klategoria_dlugosc'] = df['opis'].apply(lambda x: classify_sentence(x))


# ---------------
# Liczba słów
# -----------------------
df['liczbe_slow'] = df['opis'].apply(lambda x: len(x.split()))

df

,id,opis,klategoria_dlugosc,liczbe_slow
0,1,Małe krzesło,krótki,2
1,2,Eleganckie biurko z drewna dębowego z szufladami,krótki,7
2,3,Kompaktowy laptop do pracy biurowej z procesor...,długi,18
3,4,Lampa,krótki,1
4,5,Wygodna kanapa trzysegmentowa w kolorze szarym...,średni,9


---
### Zadanie 3 - apply z groupby

Masz dane sprzedażowe. 

Dla każdego sprzedawcy oblicz: top 3 produkty (wg sprzedaży), łączną sprzedaż, oraz czy przekroczył target 

(target = 1000zł na miesiąc). 

Zwróć jako DataFrame z podsumowaniem.

In [22]:
import pandas as pd

df = pd.DataFrame({
    'sprzedawca': ['A','A','A','A','B','B','B','C','C','C','C'],
    'produkt': ['X','Y','Z','W','X','Y','Z','X','Y','Z','W'],
    'sprzedaz': [300,150,500,200,400,600,100,200,300,400,500]
})

TARGET = 1000

# dataframe musi mieć kolumny: sprzedawca, op_produkty, suma, target_ok

In [31]:

def summarize_sales(group): # x jest ramką grupy
    # print(group) 

    # top 3 produkty
    top3 = group.nlargest(3, 'sprzedaz')['produkt'] # nlargest(n, column) gdzie n liczba największych wartości columny
    # print(top3)

    # suma sprzedazy
    suma = group['sprzedaz'].sum()

    # is target reached
    target = suma > TARGET

    return pd.DataFrame({
        'top_products': top3,
        'sum_sales': suma,
        'is_target_reached': target
    })

 
wynik = df.groupby('sprzedawca').apply(
    summarize_sales,
    include_groups=False
).reset_index(1).drop(columns=['level_1'])

wynik

           top_products  sum_sales  is_target_reached
sprzedawca
A                     Z       1150               True
A                     X       1150               True
A                     W       1150               True
B                     Y       1100               True
B                     X       1100               True
B                     Z       1100               True
C                     W       1400               True
C                     Z       1400               True
C                     Y       1400               True