### Aggregate

### Zadanie 1 - podstawowe agg 

Masz dane zamówień e-commerce. 

Oblicz per klient: 

- liczbę zamówień, 

- łączną wartość, 

- średnią wartość, 

- maksymalne i minimalne zamówienie. 
  
Użyj named aggregations (składnia pd.NamedAgg).

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'klient_id': [1,1,1,2,2,3,3,3,3],
    'zamowienie_id': range(101, 110),
    'wartosc': [250, 80, 430, 900, 150, 60, 120, 340, 90],
    'status': ['OK','OK','OK','OK','Anulowane','OK','OK','OK','Anulowane']
})

# dataframe: liczba zamówień, wartość łączna, średnia, max i min zam.

In [14]:
from IPython.display import display, Markdown
display(Markdown("### Oryginalna ramka:"))
display(df)

display(Markdown("### Ramka groupby(klient_id) + aggregate:"))
wynik = df.groupby('klient_id').agg( 
    # nowa_nazwa_kolumny=(kolumna, funkcja_agregująca)
    liczba_zamowien=('zamowienie_id', 'count'),
    wartosc_laczna=('wartosc', 'sum'),
    wartosc_srednia=('wartosc','mean'),
    wartos_max=('wartosc','max'),
    # wartos_min=('wartosc', 'min'),
    wartos_min=('wartosc',lambda x: x.min())
)

wynik

### Oryginalna ramka:

   klient_id  zamowienie_id  wartosc     status
0          1            101      250         OK
1          1            102       80         OK
2          1            103      430         OK
3          2            104      900         OK
4          2            105      150  Anulowane
5          3            106       60         OK
6          3            107      120         OK
7          3            108      340         OK
8          3            109       90  Anulowane

### Ramka groupby(klient_id) + aggregate:

,liczba_zamowien,wartosc_laczna,wartosc_srednia,wartos_max,wartos_min
klient_id,,,,,
1,3,760,253.333333,430,80
2,2,1050,525.000000,900,150
3,4,610,152.500000,340,60

In [ ]:
display(Markdown("### Ramka groupby(klient_id) + aggregate + reset_index:"))
# zapis jawny z pd.NamedAgg
wynik = df.groupby('klient_id').agg(
    liczba_zamowien=pd.NamedAgg(column='zamowienie_id', aggfunc='count'),
    wartosc_laczna=pd.NamedAgg(column='wartosc', aggfunc='sum'),
    wartosc_srednia=pd.NamedAgg(column='wartosc', aggfunc='mean'),
    wartosc_max=pd.NamedAgg(column='wartosc', aggfunc='max'),
    wartosc_min=pd.NamedAgg(column='wartosc', aggfunc=lambda x: x.min())
).reset_index() # wersja z resetowaniem klien_id to kolumny

wynik

### Ramka groupby(klient_id) + aggregate + reset_index:

,klient_id,liczba_zamowien,wartosc_laczna,wartosc_srednia,wartosc_max,wartosc_min
0,1,3,760,253.333333,430,80
1,2,2,1050,525.000000,900,150
2,3,4,610,152.500000,340,60